### ISSUE TITLE
Ansys model support (spaceclaim, disco).

### ISSUE THREAD

**Issue by mcMunich** [pyansys/pyprimemesh#377]
### 📝 Description of the feature

Since Ansys users should have access to SpaceClaim (and Discovery Geo) it would be useful to have instructions or an example on how to import a .scdoc and mesh it with pyprime. 

Since SpaceClaim can convert most any format into a scdoc (or other formats) getting pyprime to work with scdoc format would be the simplest method to drive useage. 

The .fmd format used in the examples naturally is not on the list of what SpaceClaim can create.

**Comment by waltersma** [comment]
@mcMunich the only reason SpaceClaim scdoc is not used by default in the examples is that this route is currently limited to windows OS.  SpaceClaim can export to .fmd and transfers all required inputs to PyPrimeMesh readable across different OS.

When PyPrimeMesh imports CAD geometry we have three cad reader routes available to do this. 

1. Use SpaceClaim out of process,
2. Use Workbench CAD readers out of process, or 
3. Natively import certain CAD formats that we accommodate.  

A fourth option is available that chooses the most appropriate route.  Please read [cad-reader-routes](https://prime.docs.pyansys.com/release/0.3/user_guide/fileio.html#cad-reader-routes) for a full description.

We do also provide scdoc files for most (I have noticed this is missing for pipe tee and will correct this shortly) examples that you can access by simply changing the example download function (eg. (https://prime.docs.pyansys.com/release/0.3/api/_autosummary/ansys.meshing.prime.examples.download_elbow_scdoc.html#ansys.meshing.prime.examples.download_elbow_scdoc)[prime.examples.download_elbow_scdoc()] instead of (https://prime.docs.pyansys.com/release/0.3/api/_autosummary/ansys.meshing.prime.examples.download_elbow_fmd.html#ansys.meshing.prime.examples.download_elbow_fmd)[prime.examples.download_elbow_fmd()]).  

If we added a commented line at CAD import in the examples to reference this for Windows users would this address your issue?

Thanks
